from django.conf.urls.defaults import *
from django.conf import settings



urlpatterns = patterns('',
    (r'^session1$', 'hackerhalted.appscantests.views.session1'),
    (r'^session1_login$', 'hackerhalted.appscantests.views.session1_login'),
    (r'^session1_logout$', 'hackerhalted.appscantests.views.session1_logout'),
    (r'^session1_authed$', 'hackerhalted.appscantests.views.session1_authed'),
    (r'^session1or2$', 'hackerhalted.appscantests.views.session1or2'),
    (r'^session1or2_login$', 'hackerhalted.appscantests.views.session1or2_login'),
    (r'^session1or2_logout$', 'hackerhalted.appscantests.views.session1or2_logout'),
    (r'^session1or2_authed$', 'hackerhalted.appscantests.views.session1or2_authed'),
    (r'^session3$', 'hackerhalted.appscantests.views.session3'),
    (r'^session3_login$', 'hackerhalted.appscantests.views.session3_login'),
    (r'^session3_logout$', 'hackerhalted.appscantests.views.session3_logout'),
    (r'^session3_authed$', 'hackerhalted.appscantests.views.session3_authed'),
    (r'^session4$', 'hackerhalted.appscantests.views.session4'),
    (r'^session4_login$', 'hackerhalted.appscantests.views.session4_login'),
    (r'^session4_logout$', 'hackerhalted.appscantests.views.session4_logout'),
    (r'^session4_authed$', 'hackerhalted.appscantests.views.session4_authed'),
    (r'^xss_reflected1$', 'hackerhalted.appscantests.views.xss_reflected1'),
    (r'^xss_stored1$', 'hackerhalted.appscantests.views.xss_stored1'),
    (r'^xss_stored1_get_xssdata$', 'hackerhalted.appscantests.views.xss_stored1_get_xssdata'),
    (r'^xss_stored2$', 'hackerhalted.appscantests.views.xss_stored2'),
    (r'^xss_stored3_get_xssdata$', 'hackerhalted.appscantests.views.xss_stored3_get_xssdata'),
    (r'^xss_stored3$', 'hackerhalted.appscantests.views.xss_stored3'),
    (r'^xss_stored2_get_xssdata$', 'hackerhalted.appscantests.views.xss_stored2_get_xssdata'),
    (r'^sensitiveinfo1', 'hackerhalted.appscantests.views.sensitiveinfo1'),
    (r'^sensitiveinfo2', 'hackerhalted.appscantests.views.sensitiveinfo2'),
    (r'^sensitiveinfo3', 'hackerhalted.appscantests.views.sensitiveinfo3'),
    (r'^sensitiveinfo4', 'hackerhalted.appscantests.views.sensitiveinfo4'),
    (r'^dirtraverse$', 'hackerhalted.appscantests.views.dirtraverse'),
    (r'^dirtraverse1$', 'hackerhalted.appscantests.views.dirtraverse1'),
    (r'^dirtraverse2$', 'hackerhalted.appscantests.views.dirtraverse2'),
    (r'^dirtraverse3$', 'hackerhalted.appscantests.views.dirtraverse3'), 
    (r'^dirtraverse4$', 'hackerhalted.appscantests.views.dirtraverse4'),
    (r'^dirtraverse5$', 'hackerhalted.appscantests.views.dirtraverse5'),
    (r'^dirtraverse6$', 'hackerhalted.appscantests.views.dirtraverse6'),
    (r'^dirtraverse7$', 'hackerhalted.appscantests.views.dirtraverse7'),
    (r'^fileupload$', 'hackerhalted.appscantests.views.fileupload'),
    (r'^upload_files/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.SITE_ROOT + '/upload_files','show_indexes': True}),        
#    (r'^images/(?P<image_id>\d+)_(?P<h>\d+)x(?P<w>\d+)$', 'reportgen.reports.views.reportimagethumb'),
    
)
